replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 90

image:
  repository: docker.pkg.github.com/quantu-app/quantu-app/ui
  pullPolicy: Always
  hash: sha256:2af310fac13872efeed20df46547f19616fecab261e1dd0a23bc63c5b75ad30f

env:
  NODE_ENV: production

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/secure-backends: 'true'
  hosts:
    - host: quantu.app
      paths:
        - /
  tls:
    - secretName: quantu-app-tls
      hosts:
        - quantu.app

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 128Mi
