apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantu-app.fullname" . }}
  labels: {{- include "quantu-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "quantu-app.selectorLabels" . | nindent 4 }}
