replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 60

image:
  repository: ghcr.io/quantu-app/quantu-app/quantu-app
  pullPolicy: Always
  hash: sha256:2af310fac13872efeed20df46547f19616fecab261e1dd0a23bc63c5b75ad30f

env:
  NODE_ENV: production

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/secure-backends: 'true'
  hosts:
    - host: quantu.app
      paths:
        - /
  tls:
    - secretName: quantu-app-quantu-app-tls
      hosts:
        - quantu.app

resources:
  requests:
    cpu: 800m
    memory: 100M
  limits:
    cpu: 1000m
    memory: 1000M

mongodb:
  architecture: replicaset
  replicaSetName: replicaset
  auth:
    enabled: true
    database: quantu-app
    replicaSetKey: replicasetkey
  persistence:
    enabled: true
    storageClass: linode-block-storage-retain
  rbac:
    create: true
  # externalAccess:
  #   enabled: true
  #   create: true
  #   service.type: LoadBalancer
  #   service.port: 27017
  #   autoDiscovery:
  #     enabled: true