name: Desktop

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest] # windows-latest

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: node scripts/replaceSsh.cjs
      - run: npm ci
      - run: npm run web.build
      - run: npm run desktop.prebuild
      - run: npm run desktop.binary
      - id: tag
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: '${{ steps.tag.outputs.sha_short }}'
          releaseName: 'Quant[U] ${{ steps.tag.outputs.sha_short }}'
          body: See the assets to download this version and install.
          draft: false
          prerelease: false
