name: Desktop

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: npm ci
      - run: npm run web.build
      - run: rm -r node_modules
      - run: npm i --only=production && npm i execa pkg replace-in-file
      - run: npm run desktop.build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ env.GITHUB_SHA }}
          releaseName: 'Quant[U] v${{ env.GITHUB_SHA }}'
          body: 'See the assets to download this version and install.'
          draft: true
          prerelease: false
