name: Test

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm install -g npm@8.5.3
      - run: npx playwright install
      - run: npm ci
      - run: npm test
